services:

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]  # Healthcheck for PostgreSQL
        interval: 60s
        timeout: 10s
        retries: 5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data #persisting data 
            
  pgadmin:  
    container_name: pgadmin
    image: dpage/pgadmin4
    user: root
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80 # for local browser (80 is the default port of the browsed)
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin  # Persisting pgAdmin configuration and sessions
    depends_on: 
      - db

  etl:
    container_name: etl
    build:
      context: ./etl
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 3000:3000
    volumes:
        - ./etl:/etl
    depends_on: 
      db:
        condition: service_healthy
    healthcheck:
      test: "exit 0"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: bash -c 'pip install -r /api/requirements.txt && while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    volumes:
      - ./api:/api
      - ./model:/model
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MODEL_STORAGE_PATH=/model/models
    depends_on:
      - db

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/share/nginx/html



  